export const CONNECTORS = {
  AND: 'AND',
  OR: 'OR',
  NOT: 'NOT'
}
export const DISPLAY_OPERATORS = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  CONTAINS: 'CONTAINS',
  NOT_CONTAINS: 'NOT_CONTAINS'
}
export const DISPLAY_OPERATORS_EQUALS_ONLY = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS'
}
export const DISPLAY_OPERATORS_CONTAINS_ONLY = {
  CONTAINS: 'CONTAINS',
  NOT_CONTAINS: 'NOT_CONTAINS'
}
export const OPERATORS = {
  EQUALS: 'EQUALS',
  NOT_EQUALS: 'NOT_EQUALS',
  FUNCTION: 'FUN',
  ELVIS: 'ELVIS',
  CONTAINS: 'contains',
  CONTAINS_ANY: 'containsAny',
  NOT_CONTAINS: 'NOT_CONTAINS'
}
export const TYPES = {
  OPERATION: 'OPERATION',
  NOT: 'NOT',
  MAP_OPERAND: 'MAP_OPERAND',
  FUNCTION: 'FUN',
  VAR_OPERAND: 'VAR_OPERAND'
}
export const VARIABLE_NAMES = {
  QUESTION_ANSWER: 'qa',
  GROUPS: 'groups'
}

export const SELECTION_ITEMS = {
  GROUPS: 'GROUPS',
  QUESTIONS: 'QUESTIONS'
}
